# Generated by Django 6.0.1 on 2026-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('height_sm', models.IntegerField()),
                ('eyes_color', models.CharField(max_length=255)),
                ('skin_color', models.CharField(max_length=255)),
                ('hair_color', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('face_shape', models.CharField(max_length=255)),
                ('forehead_height', models.CharField(blank=True, max_length=255)),
                ('eye_shape', models.CharField(max_length=255)),
                ('eye_size', models.CharField(blank=True, max_length=255)),
                ('nose_shape', models.CharField(blank=True, max_length=255)),
                ('lips_fullness', models.CharField(max_length=255)),
                ('chin_shape', models.CharField(blank=True, max_length=255)),
                ('brow_thickness', models.CharField(max_length=255)),
                ('brow_arch', models.CharField(blank=True, max_length=255)),
                ('undertone', models.CharField(blank=True, max_length=255)),
                ('freckles', models.BooleanField(default=False)),
                ('tanning_reaction', models.CharField(blank=True, max_length=255)),
                ('shoulders_width', models.CharField(blank=True, max_length=255)),
                ('bust', models.IntegerField(null=True)),
                ('waist', models.IntegerField(null=True)),
                ('hips', models.IntegerField(null=True)),
                ('leg_length_ratio', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
