# Generated by Django 6.0.3 on 2026-03-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
