# Generated by Django 6.0.3 on 2026-03-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_is_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_master',
        ),
    ]
