"""
Django settings for beauty_app_backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import cloudinary_storage
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root (beauty_app_backend/, same folder as manage.py).
# Requires: pip install python-dotenv (listed in requirements.txt).
_ENV_FILE = BASE_DIR / '.env'
try:
    from dotenv import load_dotenv

    load_dotenv(_ENV_FILE, encoding='utf-8')
except ImportError:
    load_dotenv = None  # type: ignore


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dl)&as3nmt3@j7293d#vzoxmg=@4vcv4%j9&ung)irn3)st#a+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- Сторонні бібліотеки ---
    'rest_framework',
    'rest_framework_simplejwt',

    # --- Мої додатки ---
    'users',
    'masters',
    'bookings',
    'chat',
    'appearance_test',

    'corsheaders',
    'cloudinary',
    'cloudinary_storage',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'beauty_app_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'beauty_app_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# PostgreSQL only — set POSTGRES_PASSWORD in beauty_app_backend/.env (see .env.example).
# Also accepts PGPASSWORD (same as the psql client).

_POSTGRES_PASSWORD = (os.getenv('POSTGRES_PASSWORD') or os.getenv('PGPASSWORD') or '').strip()
if not _POSTGRES_PASSWORD:
    _hints = [
        f'Add to {_ENV_FILE}: POSTGRES_PASSWORD=… (same folder as manage.py), or set PGPASSWORD.',
    ]
    if load_dotenv is None:
        _hints.append(
            'The python-dotenv package is not installed, so .env is ignored. Run: pip install python-dotenv',
        )
    elif _ENV_FILE.is_file():
        _hints.append(
            f'File {_ENV_FILE.name} exists — check the key is exactly POSTGRES_PASSWORD (no BOM), one line, no spaces around =.',
        )
    raise ImproperlyConfigured('PostgreSQL password is missing.\n' + '\n'.join(_hints))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'beautydb'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': _POSTGRES_PASSWORD,
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5433'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --- Django REST Framework ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# --- Simple JWT ---
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# --- Google OAuth ---
# WEB_CLIENT_ID — OAuth 2.0 Web application client ID from Google Cloud Console.
# Used to verify idTokens issued by Google Sign-In on Android (and any web flow).
# WEB_CLIENT_SECRET is only required for server-side authorization-code exchange,
# which the current Android idToken flow does not use; kept for future web flows.
GOOGLE_CLIENT_ID = os.getenv('WEB_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('WEB_CLIENT_SECRET', '')

# --- Cloudinary (profile photo upload) ---
# Set CLOUDINARY_* in beauty_app_backend/.env (see .env.example; .env is gitignored).
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET', ''),
}

CLOUDINARY_CLOUD_NAME = CLOUDINARY_STORAGE['CLOUD_NAME']
CLOUDINARY_API_KEY = CLOUDINARY_STORAGE['API_KEY']
CLOUDINARY_API_SECRET = CLOUDINARY_STORAGE['API_SECRET']

# Optional: single URL (alternative to the three vars above); also read in upload_avatar.
CLOUDINARY_URL = os.getenv('CLOUDINARY_URL', '')

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudStorage'
