# Generated by Django 6.0.3 on 2026-03-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_master_friday_hours_master_monday_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='master',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
