# Generated by Django 6.0.3 on 2026-05-13 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_master_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterreview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
